/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
/*
 * Largest prime factor
 * Problem 3
 *
 * The prime factors of 13195 are 5, 7, 13 and 29.
 *
 * What is the largest prime factor of the number 600851475143 ?
 *
*/

#include <iostream>

using namespace std;

int main()
{
    int r = 1;
    int s = 1;
    int term = 0;
    double sum = 0;

    while (r < 4000000){
        if (r%2 == 0){
            sum += r;
            //cout << r << " - " << sum << endl;
        }

        term = r;
        r += s;
        s = term;
        //cout << r << endl;
    }

    cout << sum << endl;
    printf("%f\n", sum);
    return 0;
}
